db_mysql:
  image: daocloud.io/library/mysql:latest
  restart: always
  ports:
  - '9906:3306'
  volumes:
  - /data/mysql:/var/lib/mysql
  environment:
  - VIRTUAL_HOST=db.meedesidy.top
  - MYSQL_ROOT_PASSWORD=1234